# This workflow is based on:
# https://www.nature.com/articles/s41467-023-42787-1
# and
# http://barc.wi.mit.edu/education/hot_topics/ATACseq_2024/ATACseq2024.pdf

# Only mouse and human genomes are supported for now

from scripts.resources import Resources
include: "rules/common.smk"

# Load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"



resources = Resources(config["genome"]["ensembl"], config["genome"]["release"])
SAMPLES = samples()

# Load rules
# -----------------------------------------------------
include: "rules/process_reads.smk"
include: "rules/atac.smk"

onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# Target rules
# -----------------------------------------------------
rule all:
    input:
        "results/multiqc/multiqc_report.html",
        "results/ataqv/ataqv_report.html",
        expand("results/macs2/{sample}.no_blacklist.narrowPeak", sample=SAMPLES),
