# This workflow follows the ENCODE ATAC-seq pipeline (v2.2.3):
# https://github.com/ENCODE-DCC/atac-seq-pipeline
# https://www.encodeproject.org/atac-seq/

# Only mouse and human genomes are supported for now

from scripts.resources import Resources


# Load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


include: "rules/common.smk"


resources = Resources(config["genome"]["ensembl"], config["genome"]["release"])
SAMPLES = samples()
CONDITIONS = conditions()


wildcard_constraints:
    sample="[a-zA-Z0-9_]+",
    condition="[a-zA-Z0-9_]+",
    read="R1|R2",
    prefix=r"(pooled/)?[a-zA-Z0-9_]+(\.pr[12])?",
    pair=r"rep\d+_vs_rep\d+|rep\d+-pr1_vs_rep\d+-pr2|pooled-pr1_vs_pooled-pr2",
    method="idr|overlap",


# Load rules
# -----------------------------------------------------
include: "rules/process_reads.smk"
include: "rules/atac.smk"
include: "rules/bigwig.smk"
include: "rules/qc.smk"


onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# Target rules
# -----------------------------------------------------
localrules:
    all,


rule all:
    input:
        "results/multiqc/multiqc_report.html",
        "results/ataqv_report/index.html",
        "results/qc/encode_qc_summary.tsv",
        expand(
            "results/{method}/{condition}/optimal_peak_annotated.txt",
            method=reproducibility_methods(),
            condition=CONDITIONS,
        ),
        expand(
            "results/bigwig/{prefix}.{signal}.signal.bigwig",
            prefix=SAMPLES + [f"pooled/{c}" for c in CONDITIONS],
            signal=["fc", "pval"],
        ),
