read_length: 50

genome:
  ensembl: mm39
  release: 115

trim_galore:
  extra: "-q 20 --nextera"

bwa_mem2:
  sort: "samtools" # Can be 'none', 'samtools', or 'picard'.
  sort_order: "coordinate" # Can be 'coordinate' (default) or 'queryname'.
  sort_extra: "" # Extra args for samtools/picard sorts.
  # Extra args for bwa mem2
  extra: "-M"

macs2:
  extra: "-f BAMPE --nomodel --shift -100 --extsize 200 --keep-dup all -q 0.05 -g mm"

consensus_peaks:
  method: merge # merge or multiinter
  multiinter_options:
    # Number of samples that must support a peak for it to be included in
    # the consensus peak set when using multiinter method.
    keep: 3 # minimum: 2

ataqv:
  extra: ""
