genome:
  ensembl: test
  release: 115

mito_chr_name: MT

cutadapt:
  adapter_r1: CTGTCTCTTATA
  adapter_r2: CTGTCTCTTATA
  extra: "-e 0.1 -m 5"

bowtie2:
  multimapping: 4
  extra: "-X2000 --mm"

filter:
  mapq_thresh: 30
  filter_chrs: ["MT"]

subsample_reads: 0

macs2:
  # Test genome is human chr11 only
  gsize: "1.3e8"
  pval_thresh: 0.01
  smooth_win: 150
  cap_num_peak: 300000

peaks:
  keep_chr_regex: "[0-9]+|X|Y"

idr:
  enable: true
  threshold: 0.05

pseudoreplication_random_seed: 0
